[menu]
[[menu.main]]
  identifier = 'Home'
  title = 'Home'
  url = '/'
  weight = 10

[[menu.main]]
  identifier = 'Notes'
  title = 'Notes'
  url = '/notes'
  weight = 31

[[menu.main]]
  identifier = 'TIL'
  title = 'TIL'
  url = '/til'
  weight = 32

[[menu.main]]
  identifier = 'Dialogues'
  title = 'Dialogues'
  url = '/dialogues'
  weight = 33

[[menu.main]]
  identifier = 'Articles'
  title = 'Articles'
  url = '/articles'
  weight = 34


[[menu.main]]
    identifier = 'MyTools'
    title = 'My Tools'
    url = '/mytools'
    weight = 40

[[menu.main]]
  identifier = 'IHC'
  title = 'IHC'
  url = '/ihc'
  weight = 45

[[menu.main]]
  identifier = 'Tags'
  title = 'Tags'
  url = '/tags'
  weight = 50

[params.home]
  maxArticles = 6
  maxMyTools = 6
  maxIHC = 3
  maxDialogue = 6

[params.list]
  paginate = 6

[params.articles]
  maxHoursToShowNew = 72
  maxHoursToShowUpdated = 240
